---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  # RedHat-ветка
  - name: sms-sudoers-rocky9
    image: geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
  # Debian-ветка
  - name: sms-sudoers-ubuntu2404
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..
verifier:
  name: ansible
